// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetEndpoint(arg1) {
  return window['go']['main']['FileManager']['SetEndpoint'](arg1);
}

export function UploadFile() {
  return window['go']['main']['FileManager']['UploadFile']();
}
