// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetEndpoint(arg1:string):Promise<boolean>;

export function UploadFile():Promise<string>;
