// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllFilesInfo() {
  return window['go']['main']['Request']['GetAllFilesInfo']();
}
